### ISSUE TITLE
Deleting exercise crashes app

### ISSUE THREAD

**Issue by zahin-mohammad** [power-meter/android-client#35]
- This is due to epoxy view holders having the same ID
- Epoxy view holder ID's should be unique

```E/AndroidRuntime: FATAL EXCEPTION: main
    Process: io.mochahub.powermeter, PID: 10813
    java.lang.IllegalStateException: Two different ViewHolders have the same stable ID. Stable IDs in your adapter MUST BE unique and SHOULD NOT change.
     ViewHolder 1:EpoxyViewHolder{epoxyModel=ExerciseRowModel_{exercise=Exercise(id=1, name=New Exercise, muscleGroup=New Group, personalRecord=88.0, createdAt=2019-12-07T15:23:07.940-08:00)}ExerciseRowModel_{id=-3757923307578168811, viewType=2131427431, shown=true, addedToAdapter=false}, view=com.google.android.material.card.MaterialCardView{ad2566b VFE...C.. ......ID 21,21-1059,147 #7f08008f app:id/exerciseRowContainer}, super=EpoxyViewHolder{1117872 position=0 id=-3757923307578168811, oldPos=-1, pLpos:-1}} 
     View Holder 2:EpoxyViewHolder{epoxyModel=ExerciseRowModel_{exercise=Exercise(id=5, name=New Exercise, muscleGroup=New Group, personalRecord=88.0, createdAt=2019-12-07T15:23:08.907-08:00)}ExerciseRowModel_{id=-3757923307578168811, viewType=2131427431, shown=true, addedToAdapter=false}, view=com.google.android.material.card.MaterialCardView{3a595c8 VFE...C.. ......ID 21,462-1059,588 #7f08008f app:id/exerciseRowContainer}, super=EpoxyViewHolder{29319fc position=3 id=-3757923307578168811, oldPos=-1, pLpos:-1}} com.airbnb.epoxy.EpoxyRecyclerView{cd4dd0a VFED..... ......ID 0,0-1080,1906 #7f080103 app:id/recyclerView}, adapter:com.airbnb.epoxy.EpoxyControllerAdapter@1d3e661, layout:androidx.recyclerview.widget.LinearLayoutManager@770d586, context:io.mochahub.powermeter.MainActivity@b8b0095
        at androidx.recyclerview.widget.RecyclerView.handleMissingPreInfoForChangeError(RecyclerView.java:4268)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep3(RecyclerView.java:4192)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:3862)
        at androidx.recyclerview.widget.RecyclerView.consumePendingUpdateOperations(RecyclerView.java:1897)
        at androidx.recyclerview.widget.RecyclerView$1.run(RecyclerView.java:414)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1154)
        at android.view.Choreographer.doCallbacks(Choreographer.java:977)
        at android.view.Choreographer.doFrame(Choreographer.java:885)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1139)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7682)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)```

**Comment by zahin-mohammad** [comment]
The deleting part is due to the fact that I had an old version of the app with the old db so I had a lot of duplicate exercises. To replicate on the latest build create two exercises that have the same name. We already have a `TODO` for input validation so I'll close this issue.
