### ISSUE TITLE
Crash on WorkoutSet edit 

### ISSUE THREAD

**Issue by zahin-mohammad** [power-meter/android-client#62]
Steps: 

- Try and create a new `workoutsession`
- Do not edit `date`
- Do not select `exercise`
- Start adding new sets with data for both `reps` and `weight`

Stack Trace: 
```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: io.mochahub.powermeter, PID: 13855
    com.airbnb.epoxy.ImmutableModelException: The model was changed between being added to the controller and being bound. Position: 0 Model: WorkoutRowModel_{workout=Workout(id=25043d2b-0748-4da0-bc76-df0d97611be2, exercise=Exercise(name=, personalRecord=0.0, muscleGroup=), sets=[WorkoutSet(id=055a0647-994e-4ba3-83ee-5fcdabc85371, weight=10.0, reps=20), WorkoutSet(id=de722597-a061-4f19-8047-c7aa7604b2ca, weight=10.0, reps=20), WorkoutSet(id=b9a282cc-5b21-41fe-bcad-fdb8815ac47b, weight=54.0, reps=5)]), arrayAdapter=android.widget.ArrayAdapter@9ef3b54}WorkoutRowModel_{id=-1656021425383370696, viewType=2131427434, shown=true, addedToAdapter=false}
    
    Epoxy attribute fields on a model cannot be changed once the model is added to a controller. Check that these fields are not updated, or that the assigned objects are not mutated, outside of the buildModels method. The only exception is if the change is made inside an Interceptor callback. Consider using an interceptor if you need to change a model after it is added to the controller and before it is set on the adapter. If the model is already set on the adapter then you must call `requestModelBuild` instead to recreate all models.
        at com.airbnb.epoxy.EpoxyModel.validateStateHasNotChangedSinceAdded(EpoxyModel.java:463)
        at io.mochahub.powermeter.workoutsession.workoutsessiondialog.WorkoutRowModel_.handlePreBind(WorkoutRowModel_.java:52)
        at io.mochahub.powermeter.workoutsession.workoutsessiondialog.WorkoutRowModel_.handlePreBind(WorkoutRowModel_.java:28)
        at com.airbnb.epoxy.EpoxyViewHolder.bind(EpoxyViewHolder.java:53)
        at com.airbnb.epoxy.BaseEpoxyAdapter.onBindViewHolder(BaseEpoxyAdapter.java:98)
        at com.airbnb.epoxy.BaseEpoxyAdapter.onBindViewHolder(BaseEpoxyAdapter.java:15)
        at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:7107)
        at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:6012)
        at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6279)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6118)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6114)
        at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2303)
        at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1627)
        at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1587)
        at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:675)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4134)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:3851)
        at androidx.recyclerview.widget.RecyclerView.consumePendingUpdateOperations(RecyclerView.java:1886)
        at androidx.recyclerview.widget.RecyclerView$1.run(RecyclerView.java:414)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:966)
        at android.view.Choreographer.doCallbacks(Choreographer.java:790)
        at android.view.Choreographer.doFrame(Choreographer.java:721)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:951)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

**Comment by zahin-mohammad** [comment]
@atulbipin  @brian-norman  @mridulghanshala  If you guys find a bug related to this, dump your stacktrace here and add your repro steps if you have any.
